//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace library.Exception.Book {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("library.Exception.Book.ResourceErrorMessage", typeof(ResourceErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors is required.
        /// </summary>
        public static string AUTHOR_IS_REQUIRED {
            get {
                return ResourceManager.GetString("AUTHOR_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book not found.
        /// </summary>
        public static string BOOK_NOT_FOUND {
            get {
                return ResourceManager.GetString("BOOK_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre can&apos;t be empty.
        /// </summary>
        public static string GENRE_CANT_EMPTY {
            get {
                return ResourceManager.GetString("GENRE_CANT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre is required.
        /// </summary>
        public static string GENRE_IS_REQUIRED {
            get {
                return ResourceManager.GetString("GENRE_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is required.
        /// </summary>
        public static string LANGUAGE_IS_REQUIRED {
            get {
                return ResourceManager.GetString("LANGUAGE_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published date must be less than today.
        /// </summary>
        public static string PUBLISHED_DATE_MUST_BE_LESS_THAN_TODAY {
            get {
                return ResourceManager.GetString("PUBLISHED_DATE_MUST_BE_LESS_THAN_TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published date is required.
        /// </summary>
        public static string PUBLISHED_IS_REQUIRED {
            get {
                return ResourceManager.GetString("PUBLISHED_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synopsis is required.
        /// </summary>
        public static string SYNOPSIS_IS_REQUIRED {
            get {
                return ResourceManager.GetString("SYNOPSIS_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        public static string TIITLE_IS_REQUIRED {
            get {
                return ResourceManager.GetString("TIITLE_IS_REQUIRED", resourceCulture);
            }
        }
    }
}
